workflows:
  default-workflow:
    name: Test
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: 14.3
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
        - pattern: excluded-target
          include: false
          source: false
        - pattern: included-source
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Install pre-release Swift toolchain
        script: |
          version=swift-DEVELOPMENT-SNAPSHOT-2023-04-25-a
          file_name=$version-osx.pkg
          wget https://download.swift.org/development/xcode/$version/$file_name
          xattr -dr com.apple.quarantine $file_name
          installer -pkg $file_name -target CurrentUserHomeDirectory
      - name: Test
        script: |
          export TOOLCHAINS=org.swift.59202304251a
          swift test -Xswiftc -Xfrontend -Xswiftc -dump-macro-expansions --enable-code-coverage
          xcrun llvm-cov report \
            $(swift build --show-bin-path)/SwiftPowerAssertPackageTests.xctest/Contents/MacOS/SwiftPowerAssertPackageTests \
            -instr-profile=$(swift build --show-bin-path)/codecov/default.profdata \
            -ignore-filename-regex=".build|Tests" \
            -use-color
