name: Trigger auto deployment for swift-power-assert-playground

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/swift-power-assert-playground-AutoDeployTrigger-0381146f-42d8-429c-a243-9e8204e667e2.yml"

  # Allow mannually trigger
  workflow_dispatch:

env:
  FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: swiftfiddle.azurecr.io
          username: ${{ secrets.SWIFTPOWERASSERTPLAYGROUND_REGISTRY_USERNAME }}
          password: ${{ secrets.SWIFTPOWERASSERTPLAYGROUND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        run: |
          set -ex

          cd ./Playground

          IMAGE_TAG=swiftfiddle.azurecr.io/swift-power-assert-playground:latest

          tar -czh . | docker build - --build-arg FONTAWESOME_TOKEN=${{ env.FONTAWESOME_TOKEN }} --rm --tag ${IMAGE_TAG}
          docker push ${IMAGE_TAG}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SWIFTPOWERASSERTPLAYGROUND_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n swift-power-assert-playground -g swiftfiddle --server swiftfiddle.azurecr.io --username  ${{ secrets.SWIFTPOWERASSERTPLAYGROUND_REGISTRY_USERNAME }} --password ${{ secrets.SWIFTPOWERASSERTPLAYGROUND_REGISTRY_PASSWORD }}
            az containerapp update -n swift-power-assert-playground -g swiftfiddle --image swiftfiddle.azurecr.io/swift-power-assert-playground:latest
