name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Install Swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-07-a
      - uses: actions/checkout@v3
      - name: Build
        run: |
          export TOOLCHAINS=org.swift.59202305071a
          swift build
      - name: Run tests
        run: |
          swift test -Xswiftc -Xfrontend -Xswiftc -dump-macro-expansions --enable-code-coverage
      - name: Gather code coverage
        run: |
          BUILD_PATH=$(swift build --show-bin-path)
          xcrun llvm-cov report \
            $BUILD_PATH/SwiftPowerAssertPackageTests.xctest/Contents/MacOS/SwiftPowerAssertPackageTests \
            -instr-profile=$BUILD_PATH/codecov/default.profdata \
            -ignore-filename-regex=".build|Tests" -use-color
          xcrun llvm-cov export -format="lcov" \
            $BUILD_PATH/SwiftPowerAssertPackageTests.xctest/Contents/MacOS/SwiftPowerAssertPackageTests \
            -instr-profile=$BUILD_PATH/codecov/default.profdata \
            -ignore-filename-regex=".build|Tests" > coverage_report.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: fail
          files: ./coverage_report.lcov
          verbose: true
