name: Update Swift Package

on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
      - name: Swift Version
        id: swift-version
        run: echo "SWIFT_VERSION=$(cat .swift-version)" >> "$GITHUB_OUTPUT"
      - name: Install Swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: ${{ steps.swift-version.outputs.SWIFT_VERSION }}
      - name: Update Swift Package
        run: |
          set -ex
          export TOOLCHAINS=swift
          swift package update --package-path ./
          swift package update --package-path Example/
          swift package update --package-path Playground/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          base: "main"
          commit-message: "Update Swift Packages"
          title: "Update Swift Packages"
          add-paths: |
            Package.resolved
            **/Package.resolved
